/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample.producer;

import com.google.common.collect.Multiset;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
