/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample.consumer;

//import com.google.common.collect.Multiset;
import com.sample.producer.Library;


public class LibraryImpl implements Library {

    @Override
    public boolean someLibraryMethod() {
        return true;
    }
}
